### ISSUE TITLE
font-family at class="ag-courses-item_title" and class="intro-con

### ISSUE THREAD

**Issue by SigmaMind-Research** [SigmaMind-Research/sigmamind#3]
change the font family to Space Grotesk @annavarughese 

`<span class="intro-con"> Discover the future of chest X-ray analysis with RadioX <br> </span>
                </div>
                <div class="col-md-6">
                  <div class="bgc">
                  </div>
                </div>
                <div class="ag-format-container">
                <div class="ag-courses_box">
                  <div class="ag-courses_item">
                    <a href="#" class="ag-courses-item_link">
                      <div class="ag-courses-item_bg"></div>

                      <div class="ag-courses-item_title">
                      Our revolutionary AI-powered app leverages cutting edge AI technology to predict  and analyze chest diseases with unmatched accuracy and speed.
                            </div>
                          </a>
                        </div>
                      <div class="ag-courses_item">
                        <a href="#" class="ag-courses-item_link">
                          <div class="ag-courses-item_bg"></div>

                          <div class="ag-courses-item_title">
                          Say goodbye to manual intepretations and long waiting times.With RadioX, healthcare professionals can make informed decisions and provide timely care to patients.
                                </div>
                              </a>
                            </div>
                          <div class="ag-courses_item">
                            <a href="#" class="ag-courses-item_link">
                              <div class="ag-courses-item_bg"></div>

                              <div class="ag-courses-item_title">
                              Join us on this transformative journey as we redifine the field of radiology and improve patient outcomes.
                                    </div>
                                  </a>
                                </div>
                              </div>
                            </div>`

**Comment by annavarughese** [comment]
Made the required changes, kindly verify and let me know

**Comment by SigmaMind-Research** [comment]
change the font family in body (style.css file) then it will reflect
