### ISSUE TITLE
nav bar is not responsive

### ISSUE THREAD

**Issue by SigmaMind-Research** [SigmaMind-Research/sigmamind#4]
@annavarughese when we do inspect on browser the nav bar wont change acc to the device.

**Comment by annavarughese** [comment]
The nav bar only has one element, so I didn't really understand the issue.

**Comment by SigmaMind-Research** [comment]
@annavarughese do inspect in browser where you change the device or ratio of the website then About button will not be responsible
![_C__test_website_launch_index html (1)](https://github.com/Friday-labs/launch/assets/116866451/71c38c74-69ed-47d8-ab90-e66641771086)
